a = {
    "status_code": 200,
    "msg": "success",
    "result": {
        "qeeka_coins": 382,
        "free_cash": 0.0,
        "daily_logs": {
            "total_count": 7,
            "sign_status": 1,
            "sign_coin": 2,
            "sign_days": 1,
            "total_days": 2,
            "logs": [{
                "date": "今日",
                "status": 1,
                "coin_value": 2
            }, {
                "date": "02-26",
                "status": 0,
                "coin_value": 6
            }, {
                "date": "02-27",
                "status": 0,
                "coin_value": 8
            }, {
                "date": "02-28",
                "status": 0,
                "coin_value": 10
            }, {
                "date": "03-01",
                "status": 0,
                "coin_value": 12
            }, {
                "date": "03-02",
                "status": 0,
                "coin_value": 15
            }, {
                "date": "03-03",
                "status": 0,
                "coin_value": 18
            }],
            "sign_extra_status": false,
            "sign_extra_points": 600
        },
        "daily_tasks": {
            "total_count": 53,
            "task_finished_count": 1,
            "task_percent": "0.0",
            "task_list": [{
                "icon_url": "http://imgmall.tg.com.cn/kol/2023/02/13/1037/TTiXnyHcQeETEp4sKZSzCnpHTM5T.png",
                "action_cn": "写日记",
                "task_name": "写装修日记，立得奖励！",
                "task_tip": "50齐家币/篇",
                "get_points": "50",
                "finished_count": 5,
                "total_count": 5,
                "button_text": "写日记",
                "status": 1,
                "task_link": "zxtt://open/native?params={\"url\":\"create_diary\"}",
                "clickable": 0
            }, {
                "icon_url": "http://imgmall.tg.com.cn/kol/2023/02/13/1037/DWkwRkKCDZdxNyfp8PSypcnhZh68.png",
                "action_cn": "发帖",
                "task_name": "发表我的装修看法，立得奖励！",
                "task_tip": "10齐家币/次",
                "get_points": "10",
                "finished_count": 0,
                "total_count": 5,
                "button_text": "去发表",
                "status": 0,
                "task_link": "zxtt://open/native?params={\"url\":\"post_beautiful_photo_video\"}",
                "clickable": 1
            }, {
                "icon_url": "http://imgmall.tg.com.cn/kol/2023/02/13/1037/mz2MFFEND2EQJNbCYf7572sz62Fm.png",
                "action_cn": "评论",
                "task_name": "对喜欢的内容评论，立得奖励！",
                "task_tip": "2齐家币/次",
                "get_points": "2",
                "finished_count": 0,
                "total_count": 10,
                "status": 0,
                "task_link": "zxtt://open/native?params={\"url\":\"home_page\",\"data\":{\"open_tab_key\":\"tab_luntan\"}}",
                "clickable": 1
            }]
        },
        "un_finish_task": 52,
        "new_push_status": 0,
        "show_more": 1,
        "show_ability_test": 0,
        "show_lottery": 0,
        "un_finish_task_count": 2,
        "can_get_coin": 70,
        "skip_validation": false,
        "share": {
            "share_title": "签到赢大奖，人人有，天天有，连续签到还翻番哦~",
            "share_desc": "",
            "share_link": "/pages/activity/signIn/signIn",
            "share_img_url": "https://mued3.jia.com/image/TaroAggregate/qijiapro/gift/sign-in-share.png",
            "sign": "",
            "share_text": "",
            "mini_program_id": "gh_76be1493b1f9"
        },
        "tip_list": ["卡密使用方法：", "网页版：", "1.官网http://www.iqiyi.com/-登陆自己的爱奇艺账号-立即开通-点击兑换代金券-输入兑换码即可。", "安卓：", "1.打开爱奇艺APP-我的-我的vip会员-立即续费-激活码兑换-输入激活码和验证码-提交-激活成功。", "iOS:", "1.关注爱奇艺微信公众号。", "2.点击呼叫小秘-开通会员-代金券。", "3.点击兑换代金券-输入代金券兑换码。"]
    }
}