result = {
    "info": {
        "produced": {
            "own_tribute": "1",
            "time": 0
        },
        "friend": {
            "all_speed": 1,
            "group": [{
                "id": "1864",
                "member_id": "1969",
                "downline_id": "435",
                "level": "1",
                "currency": "7",
                "type": "2",
                "is_auth": "2",
                "uniacid": "16",
                "updated": "1654852853",
                "created": "1654850613",
                "member": {
                    "id": "435",
                    "unionid": "",
                    "uniacid": "16",
                    "openid": "2021013041327194914316",
                    "nickname": "天天养牛",
                    "headimgurl": "https:\/\/xyx.zlzw188.com\/attachment\/images\/16\/2021\/01\/WQ8jQ38B8Q0003gd0jx1QWD18qszN6.gif",
                    "sex": "0",
                    "country": "",
                    "province": "",
                    "city": "",
                    "parent_id": "0",
                    "money": "0.00",
                    "warehouse": "0",
                    "warehouse_level": "0",
                    "foodstuff": "0",
                    "currency": "69292",
                    "is_block": "1",
                    "phone": "",
                    "is_fictitious": "2",
                    "is_receive": "1",
                    "payment_code": "",
                    "cash": "0",
                    "qq": "",
                    "shop_id": "0",
                    "last_login_time": "0",
                    "bonus_level": "1",
                    "is_bonus": "1",
                    "risk_rank": "-1",
                    "created": "1611995429"
                },
                "end": 1
            }]
        },
        "warehouse_currency": "101",
        "member": {
            "id": "1969",
            "unionid": "",
            "uniacid": "16",
            "openid": "oj_md4qsHJcKwTsWoVO0rqx-vrbQ",
            "nickname": "夢里夢",
            "headimgurl": "https:\/\/thirdwx.qlogo.cn\/mmopen\/vi_32\/xllrFUY8aNxbbicoysgIDTOwwzkfDYRH4ic9CrIicQYFfuwq5U46f6ZXkQicdicG1HktIg0SYWKp4fVnvicCaLcQ4lmA\/132",
            "sex": "0",
            "country": "",
            "province": "",
            "city": "",
            "parent_id": "1930",
            "money": "0.00",
            "warehouse": "101",
            "warehouse_level": "0",
            "foodstuff": "1",
            "currency": "1812",
            "is_block": "1",
            "phone": "",
            "is_fictitious": "1",
            "is_receive": "2",
            "payment_code": "",
            "cash": "0",
            "qq": "",
            "shop_id": "0",
            "last_login_time": "1654857650",
            "bonus_level": "1",
            "is_bonus": "1",
            "risk_rank": "-1",
            "created": "1654764642"
        },
        "collect_currency": 0,
        "loading": true,
        "share": {
            "member_id": "1969",
            "text": "在线养牛可以兑换牛奶，现金红包，看看谁是2021年养牛达人，牛年行大运！牛转乾坤！牛气冲天！",
            "images": "",
            "nav_bg_color": "#4DB34D"
        }
    },
    "status": 1
}



console.log(result.info.member.nickname);



aaa = {
    "info": {
        "member": {
            "id": "1969",
            "unionid": "",
            "uniacid": "16",
            "openid": "oj_md4qsHJcKwTsWoVO0rqx-vrbQ",
            "nickname": "夢里夢",
            "headimgurl": "https:\/\/thirdwx.qlogo.cn\/mmopen\/vi_32\/xllrFUY8aNxbbicoysgIDTOwwzkfDYRH4ic9CrIicQYFfuwq5U46f6ZXkQicdicG1HktIg0SYWKp4fVnvicCaLcQ4lmA\/132",
            "sex": "0",
            "country": "",
            "province": "",
            "city": "",
            "parent_id": "1930",
            "money": "0.00",
            "warehouse": "101",
            "warehouse_level": "0",
            "foodstuff": "0",
            "currency": "2295",
            "is_block": "1",
            "phone": "",
            "is_fictitious": "1",
            "is_receive": "2",
            "payment_code": "",
            "cash": "0",
            "qq": "",
            "shop_id": "0",
            "last_login_time": "1654862213",
            "bonus_level": "1",
            "is_bonus": "1",
            "risk_rank": "-1",
            "created": "1654764642"
        },
        "images": {
            "currency": "https:\/\/xyx.zlzw188.com\/attachment\/images\/16\/2021\/01\/KXc061y0kx1Oo1C6kB06oQ55xb6G1O.png",
            "food": "https:\/\/xyx.zlzw188.com\/attachment\/images\/16\/2021\/01\/CshvSSZMr53KSAr34sHsHHkefwhKZw.gif",
            "sign": "https:\/\/xyx.zlzw188.com\/addons\/bh_cat\/template\/static\/images\/xcx\/sign.png",
            "friend_c": "https:\/\/xyx.zlzw188.com\/addons\/bh_cat\/template\/static\/images\/xcx\/friend_c.png",
            "cl": "https:\/\/xyx.zlzw188.com\/addons\/bh_cat\/template\/static\/images\/xcx\/cl.png",
            "zyADbc": "https:\/\/xyx.zlzw188.com\/addons\/bh_cat\/template\/static\/images\/xcx\/gzhbg.png",
            "giftbag": "https:\/\/xyx.zlzw188.com\/addons\/bh_cat\/template\/static\/images\/xcx\/gift_box.png",
            "beginClick_v3": "https:\/\/xyx.zlzw188.com\/addons\/bh_cat\/template\/static\/images\/xcx\/beginClick_v3.png",
            "redbag_bg": "https:\/\/xyx.zlzw188.com\/addons\/bh_cat\/template\/static\/images\/xcx\/redbag_bg.png",
            "avatar_frame": "https:\/\/xyx.zlzw188.com\/addons\/bh_cat\/template\/static\/images\/xcx\/avatar_frame.png",
            "pets_image": "https:\/\/xyx.zlzw188.com\/attachment\/images\/16\/2021\/01\/WQ8jQ38B8Q0003gd0jx1QWD18qszN6.gif",
            "home_bg": "https:\/\/xyx.zlzw188.com\/attachment\/images\/16\/2021\/01\/h7OULLXLLllWLxOBpxxGuUfn7oLjbZ.jpg",
            "login_image": "https:\/\/xyx.zlzw188.com\/addons\/bh_cat\/template\/static\/images\/xcx\/pic010.png"
        },
        "fictitious": false,
        "config": {
            "food_name": "牛奶",
            "video_food_start": "1",
            "video_food_end": "1",
            "daily_video_num": "3",
            "share_daily_num": "10",
            "share_food": "1",
            "xcx_title": "养牛换宝",
            "give_text": "赠送牛币",
            "currency_name": "牛币",
            "video_ad": "adunit-fb4f659770d4dbf8",
            "own_tribute": "1",
            "home_bg_color": "#4DB34D",
            "home_button_color": "#e3920f",
            "home_video_ad": "adunit-ef0357e499f150e0",
            "screen_ad": "adunit-ef0357e499f150e0",
            "own_tribute_time": "2",
            "pay_tribute_time": "10",
            "xcx_image": "",
            "full_physical_time": 360,
            "tmplIds": ["yCNm1vrASZn5RY5kH2l3hcHwTFn0qtZcMOWVPvzN-Bw", "ix8mkYaFBdJYgrGzRyPtKoo145_PQkSzlsw9FsTxa10"],
            "click_feed_txt": "点击喂食",
            "my_physical": "我的体力",
            "sign_double_txt": "点击奖励翻倍",
            "free_now_txt": "立即免费领取",
            "single_ad": "adunit-89d83c895b4f94d2",
            "open_dividend": "1",
            "is_collect_ad": "2",
            "feeding_reminder": "6_7PooAaxhJyxgo3xi6djeVrY2JscnyP44gjfIEOPdc",
            "goods_flow_group": "adunit-3dfcad2a119eec34",
            "is_home_banner": "2",
            "onekey_txt": "一键收取您的好友进贡牛币",
            "every_day_collar": "任务大厅",
            "friends_pay": "好友进贡牛币",
            "watch_video_txt": "观看激励视频",
            "watch_video_reward_txt": "1-3G喂养牛奶→",
            "share_friend_reward_txt": "1000+牛币奖励→",
            "hot_application_txt": "下方广告位招租，可跳转其他小程序↓",
            "home_user_bg_color": "#e3920f",
            "home_coin_bg_color": "#e3920f",
            "dividends_account_id": "ybsUwPt-jSWK6K6QqfV4SB75MRhgCPBVCQoSdvgNp_o",
            "ad_fail_txt": "暂没有视频，等会再试试！"
        },
        "look_num": "3",
        "share_num": 0,
        "daily_food": {
            "status": true,
            "daily_food": "1"
        },
        "is_sign": true,
        "is_auth": true,
        "video_time": 0,
        "dy": ["G3wABxz9_3UabseNTPKyTwkGNvXSMlXM2MsmnBSANrg", "ybsUwPt-jSWK6K6QqfV4SB75MRhgCPBVCQoSdvgNp_o", "ybsUwPt-jSWK6K6QqfV4SB75MRhgCPBVCQoSdvgNp_o"],
        "bonus_info": {
            "current": {
                "id": "5",
                "level": "1",
                "level_name": "萌牛",
                "level_image": "https:\/\/xyx.zlzw188.com\/attachment\/images\/16\/2021\/01\/w6SGGgdAmZ557GM9WMOSZF51H5w37c.png",
                "share_number": "0",
                "integral": "1000",
                "proportion": "1",
                "money": "0.00",
                "uniacid": "16",
                "created": "1611660891"
            },
            "next": {
                "id": "6",
                "level": "2",
                "level_name": "红牛",
                "level_image": "https:\/\/xyx.zlzw188.com\/attachment\/images\/16\/2021\/01\/UmwQABBOJDAB6oa2wqbnqR6Z22DZrs.png",
                "share_number": 1,
                "integral": "10000",
                "proportion": "3",
                "money": "0.00",
                "uniacid": "16",
                "created": "1611660919"
            },
            "today_dividend": 10,
            "my_dividend": false,
            "member_share": "0",
            "speed": 23
        },
        "loading": true,
        "share": {
            "member_id": "1969",
            "text": "在线养牛可以兑换牛奶，现金红包，看看谁是2021年养牛达人，牛年行大运！牛转乾坤！牛气冲天！",
            "images": "",
            "nav_bg_color": "#4DB34D"
        },
        "navigation_list": [{
            "id": "4",
            "name": "首页",
            "position": "index_home",
            "path": "\/bh_cat\/pages\/index\/index",
            "selection_image": "images\/16\/2021\/01\/kP9dc8COrTyK6KRCGCt6hpfLcdg9p4.png",
            "unchecked_images": "images\/16\/2021\/01\/o76Dbm7hhCGBaABGA06Ah7C77L8K7b.png",
            "selection_color": "",
            "unchecked_color": "",
            "sort": "5",
            "uniacid": "16",
            "created": "1611662328",
            "selectd": true,
            "image": "https:\/\/xyx.zlzw188.com\/attachment\/images\/16\/2021\/01\/kP9dc8COrTyK6KRCGCt6hpfLcdg9p4.png",
            "color": ""
        }, {
            "id": "5",
            "name": "兑换",
            "position": "shop_index",
            "path": "\/bh_cat\/pages\/goodsconvert\/goodsconvert",
            "selection_image": "images\/16\/2021\/01\/Q8xhs4by1b13GT8GZtwT833S1WYh1w.png",
            "unchecked_images": "images\/16\/2021\/01\/Q8xhs4by1b13GT8GZtwT833S1WYh1w.png",
            "selection_color": "",
            "unchecked_color": "",
            "sort": "4",
            "uniacid": "16",
            "created": "1611662358",
            "selectd": false,
            "image": "https:\/\/xyx.zlzw188.com\/attachment\/images\/16\/2021\/01\/Q8xhs4by1b13GT8GZtwT833S1WYh1w.png",
            "color": ""
        }, {
            "id": "8",
            "name": "商城",
            "position": "pdd_category",
            "path": "\/bh_cat\/pages\/pdd\/pdd",
            "selection_image": "images\/16\/2021\/01\/DPgl493f9ttz43tTofGwGAZ4L3t99b.jpg",
            "unchecked_images": "images\/16\/2021\/01\/DPgl493f9ttz43tTofGwGAZ4L3t99b.jpg",
            "selection_color": "",
            "unchecked_color": "",
            "sort": "3",
            "uniacid": "16",
            "created": "1611915291",
            "selectd": false,
            "image": "https:\/\/xyx.zlzw188.com\/attachment\/images\/16\/2021\/01\/DPgl493f9ttz43tTofGwGAZ4L3t99b.jpg",
            "color": ""
        }, {
            "id": "7",
            "name": "文章",
            "position": "news_index",
            "path": "\/bh_cat\/pages\/news\/news",
            "selection_image": "images\/16\/2021\/01\/Qi9EX59tXteI6xUO4DCDZIg63eSesz.png",
            "unchecked_images": "images\/16\/2021\/01\/KXc061y0kx1Oo1C6kB06oQ55xb6G1O.png",
            "selection_color": "",
            "unchecked_color": "",
            "sort": "2",
            "uniacid": "16",
            "created": "1611662447",
            "selectd": false,
            "image": "https:\/\/xyx.zlzw188.com\/attachment\/images\/16\/2021\/01\/KXc061y0kx1Oo1C6kB06oQ55xb6G1O.png",
            "color": ""
        }, {
            "id": "6",
            "name": "我的",
            "position": "my_index",
            "path": "\/bh_cat\/pages\/my\/my",
            "selection_image": "images\/16\/2021\/01\/jjJ8joP84oyRp4JP8Zzr8RPY8rI5JP.png",
            "unchecked_images": "images\/16\/2021\/01\/nLiCYx2YtHi20H3Ma00Y3X2a0vYs0m.png",
            "selection_color": "",
            "unchecked_color": "",
            "sort": "1",
            "uniacid": "16",
            "created": "1611662383",
            "selectd": false,
            "image": "https:\/\/xyx.zlzw188.com\/attachment\/images\/16\/2021\/01\/nLiCYx2YtHi20H3Ma00Y3X2a0vYs0m.png",
            "color": ""
        }]
    },
    "status": 1
}



bbb = {
    "info": {
        "task": {
            "s": [{
                "id": "16",
                "title": "点我领500牛币！",
                "describe": "天天领牛币！",
                "icon": "https:\/\/xyx.zlzw188.com\/attachment\/images\/16\/2021\/01\/jjJ8joP84oyRp4JP8Zzr8RPY8rI5JP.png",
                "type": "1",
                "time": "0",
                "reward": "500",
                "appid": "",
                "path": "",
                "position": "1",
                "sort": "2",
                "reward_type": "1",
                "number": "100",
                "uniacid": "16",
                "created": "1612495133"
            }, {
                "id": "15",
                "title": "领取500牛币",
                "describe": "天天领牛币！",
                "icon": "https:\/\/xyx.zlzw188.com\/attachment\/images\/16\/2021\/01\/Qi9EX59tXteI6xUO4DCDZIg63eSesz.png",
                "type": "1",
                "time": "0",
                "reward": "500",
                "appid": "",
                "path": "",
                "position": "1",
                "sort": "1",
                "reward_type": "1",
                "number": "100",
                "uniacid": "16",
                "created": "1611975799"
            }],
            "d": []
        },
        "loading": true,
        "share": {
            "member_id": "3258",
            "text": "在线养牛可以兑换牛奶，现金红包，看看谁是2021年养牛达人，牛年行大运！牛转乾坤！牛气冲天！",
            "images": "",
            "nav_bg_color": "#4DB34D"
        }
    },
    "status": 1
}