a = {
    "code": "success",
    "data": {
        "userId": "1602268346196365312",
        "userName": "smarterKSVWD",
        "pinyin": "smarterKSVWD",
        "avatar": "https://app-obs-prod.smart.cn/avatars/2022/12/20/1602268346196365312xx1671523449262.jpg",
        "thumbnail": "https://app-obs-prod.smart.cn/avatars/2022/12/20/1602268346196365312xx1671523449262.jpg",
        "provinceCode": "320000",
        "provinceName": "江苏省",
        "cityCode": "320600",
        "cityName": "南通市",
        "role": "fans",
        "roleId": null,
        "official": false,
        "badges": null,
        "office": null,
        "blacklist": false,
        "blacklists": [],
        "deleted": false,
        "violateId": null,
        "appealStatus": null,
        "operator": 0,
        "cleanPublish": false,
        "ownerIdentity": [
            "10",
            "20"
        ],
        "bgImage": null,
        "signature": "呵呵呵",
        "sex": "M",
        "birthday": 704908800000,
        "phone": "15295065582",
        "wechatId": "oWAvd5SLZPxaMnIili1l1JARXh8A",
        "wechatUnionId": "oiRgW6t8qQnp4yU_VXOQNEoTx-Ek",
        "wechatName": null,
        "wechatAvatar": null,
        "weiboId": null,
        "weiboName": null,
        "weiboAvatar": null,
        "appleId": null,
        "appleName": null,
        "appleAvatar": null,
        "email": null,
        "searchByMobile": true,
        "blacklistReason": null,
        "blacklistTime": null,
        "hobby": [],
        "momentsCount": 0,
        "articlesCount": 0,
        "questionsCount": 0,
        "photosCount": 0,
        "visibility": "all",
        "imToken": "Jhib7Qor1WUj9MjEjuzEbtoIB5dBi23BEBoPM+zhKkYg758+hFam47sL1YWq2aIQ@x5xb.cn.rongnav.com;x5xb.cn.rongcfg.com",
        "welcomeTime": 1671165442740,
        "isAuthenticated": false,
        "addBlacklistCount": null,
        "areaCode": "320613",
        "areaName": "崇川区",
        "attestationStatus": null,
        "name": null,
        "identificationNumber": null,
        "completedFillInfo": true,
        "source": null,
        "focusModels": [
            "HX11"
        ],
        "bookIngModels": null,
        "contactsCount": 0,
        "fansCount": 0,
        "violateCount": 0,
        "blacklistCount": 0,
        "favoritesCount": 0,
        "momentsUnpublishCount": 0,
        "articlesUnpublishCount": 0,
        "associationsCount": 0,
        "associationsUnpublishCount": 0,
        "joinedActivitiesCount": 0,
        "createdBy": {
            "userId": "1602268346196365312",
            "userName": "smarterKSVWD",
            "pinyin": "smarterKSVWD",
            "avatar": "https://app-obs-prod.smart.cn/avatars/2022/12/20/1602268346196365312xx1671523449262.jpg",
            "thumbnail": "https://app-obs-prod.smart.cn/avatars/2022/12/20/1602268346196365312xx1671523449262.jpg",
            "provinceCode": "320000",
            "provinceName": "江苏省",
            "cityCode": "320600",
            "cityName": "南通市",
            "role": "fans",
            "roleId": null,
            "official": false,
            "badges": null,
            "office": null,
            "blacklist": false,
            "blacklists": [],
            "deleted": false,
            "violateId": null,
            "appealStatus": null,
            "operator": 0,
            "cleanPublish": false,
            "ownerIdentity": [
                "10",
                "20"
            ]
        },
        "createTime": 1670845517120,
        "updatedBy": {
            "userId": "1602268346196365312",
            "userName": "smarterKSVWD",
            "pinyin": "smarterKSVWD",
            "avatar": "https://app-obs-prod.smart.cn/avatars/2022/12/20/1602268346196365312xx1671523449262.jpg",
            "thumbnail": "https://app-obs-prod.smart.cn/avatars/2022/12/20/1602268346196365312xx1671523449262.jpg",
            "provinceCode": "320000",
            "provinceName": "江苏省",
            "cityCode": "320600",
            "cityName": "南通市",
            "role": "fans",
            "roleId": null,
            "official": false,
            "badges": null,
            "office": null,
            "blacklist": false,
            "blacklists": [],
            "deleted": false,
            "violateId": null,
            "appealStatus": null,
            "operator": 0,
            "cleanPublish": false,
            "ownerIdentity": [
                "10",
                "20"
            ]
        },
        "updateTime": 1673830906095,
        "signTime": 1673830906094,
        "signCount": 32,
        "blacklistOperator": null,
        "realNames": [
            {
                "name": "顾**",
                "identificationNumber": "321***********3613",
                "identificationType": 0
            }
        ],
        "createDate": 1670774400000,
        "integral": 6125,
        "growth": 25,
        "medal": 2,
        "improved": false,
        "hobbyList": null,
        "config": {
            "videoCompressionConf": {
                "compressionQuality": "DefaultQuality",
                "maxValue": 150,
                "maxDuration": 300
            }
        },
        "needFillInfos": false,
        "fillInfoSwitch": false
    },
    "message": null,
    "requestId": "44d3657c1a8473e324ba8b8783f8b8d8"
}