tasklist = {
  state: true,
  data: {
    integral: {
      integral: "1003",
      signnum: "1",
      sign: 1,
      consume_count: [
        {
          rule_id: "1",
          point: "1000",
          member_id: "773754",
          current_times: "1",
        },
        {
          rule_id: "2",
          point: "1",
          member_id: "773754",
          current_times: "1",
        },
        {
          rule_id: "13",
          point: "2",
          member_id: "773754",
          current_times: "1",
        },
      ],
      count: 1003,
      current_day_points: 39,
      complete_sign_points: 100,
      rule: [
        {
          id: "1",
          name: "注册成功",
          action_sign: "SYS_REGISTER",
          type: "0",
          cycle_type: "0",
          cycle_time: "0",
          point: "1000",
          reward_num: "1",
          status: "1",
          is_show: 1,
          count: "1000",
          current_times: "1",
          total_points: 1000,
        },
        {
          id: "2",
          name: "每日登录",
          action_sign: "SYS_LOGIN",
          type: "0",
          cycle_type: "1",
          cycle_time: "0",
          point: "1",
          reward_num: "1",
          status: "1",
          is_show: "1",
          count: "1",
          current_times: "1",
          total_points: 1,
        },
        {
          id: "3",
          name: "阅读资讯",
          action_sign: "SYS_READ",
          type: "0",
          cycle_type: "1",
          cycle_time: "0",
          point: "1",
          reward_num: "1",
          status: "1",
          is_show: "1",
          count: 0,
          current_times: 0,
          total_points: 1,
        },
        {
          id: "4",
          name: "发布评论",
          action_sign: "SYS_COMMENT",
          type: "0",
          cycle_type: "1",
          cycle_time: "0",
          point: "2",
          reward_num: "1",
          status: "1",
          is_show: "1",
          count: 0,
          current_times: 0,
          total_points: 2,
        },
        {
          id: "5",
          name: "点赞",
          action_sign: "SYS_LIKE",
          type: "0",
          cycle_type: "1",
          cycle_time: "0",
          point: "1",
          reward_num: "6",
          status: "1",
          is_show: "1",
          count: 0,
          current_times: 0,
          total_points: 6,
        },
        {
          id: "6",
          name: "分享",
          action_sign: "SYS_SHARE",
          type: "0",
          cycle_type: "1",
          cycle_time: "0",
          point: "3",
          reward_num: "3",
          status: "1",
          is_show: "1",
          count: 0,
          current_times: 0,
          total_points: 9,
        },
        {
          id: "7",
          name: "收藏资讯",
          action_sign: "SYS_COLLECT",
          type: "0",
          cycle_type: "1",
          cycle_time: "0",
          point: "1",
          reward_num: "1",
          status: "1",
          is_show: "1",
          count: 0,
          current_times: 0,
          total_points: 1,
        },
        {
          id: "12",
          name: "邀请",
          action_sign: "CUSTOM_YAOQING",
          type: "2",
          cycle_type: "1",
          cycle_time: "0",
          point: "1",
          reward_num: "1",
          status: "1",
          is_show: 0,
          count: 0,
          current_times: 0,
          total_points: 1,
        },
        {
          id: "13",
          name: "签到",
          action_sign: "CUSTOM_QIANDAO",
          type: "0",
          cycle_type: "1",
          cycle_time: "0",
          point: "2",
          reward_num: "1",
          status: "1",
          is_show: 0,
          count: "2",
          current_times: "1",
          total_points: 2,
        },
        {
          id: "17",
          name: "观看视频",
          action_sign: "CUSTOM_WATCH_VIDEO",
          type: "2",
          cycle_type: "1",
          cycle_time: "0",
          point: "1",
          reward_num: "1",
          status: "1",
          is_show: "1",
          count: 0,
          current_times: 0,
          total_points: 1,
        },
        {
          id: "18",
          name: "发布动态",
          action_sign: "CUSTOM_PLUS_FEED",
          type: "2",
          cycle_type: "1",
          cycle_time: "0",
          point: "5",
          reward_num: "1",
          status: "1",
          is_show: "1",
          count: 0,
          current_times: 0,
          total_points: 5,
        },
        {
          id: "19",
          name: "飞卡阅读",
          action_sign: "CUSTOM_READ_CARD_NEWS",
          type: "2",
          cycle_type: "1",
          cycle_time: "0",
          point: "1",
          reward_num: "10",
          status: "1",
          is_show: "1",
          count: 0,
          current_times: 0,
          total_points: 10,
        },
      ],
      signPoints: [2, 3, 4, 5, 6, 7, 8],
    },
  },
};

