aaa = {
	"result": 1,
	"data": {
		"nebulaSignInPopup": {
			"title": "今日签到加1000快乐豆",
			"subTitle": "当日提现秒到账",
			"cornerText": "",
			"button": "立即签到",
			"awardList": [
				{
					"day": 1,
					"coin": 0,
					"multiple": 0,
					"bottomText": "1天",
					"topText": "",
					"lastSignDay": false,
					"iconType": 8,
					"signed": true,
					"today": false,
					"supplySignMultiple": 0,
					"cornerText": "",
					"highLight": false,
					"award": "1000",
					"awardType": 2,
					"awardUnit": ""
				},
				{
					"day": 2,
					"coin": 0,
					"multiple": 0,
					"bottomText": "签到可领",
					"topText": "",
					"lastSignDay": false,
					"iconType": 8,
					"signed": false,
					"today": true,
					"supplySignMultiple": 0,
					"cornerText": "",
					"highLight": false,
					"award": "1000",
					"awardType": 2,
					"awardUnit": ""
				},
				{
					"day": 3,
					"coin": 0,
					"multiple": 0,
					"bottomText": "3天",
					"topText": "",
					"lastSignDay": false,
					"iconType": 6,
					"signed": false,
					"today": false,
					"supplySignMultiple": 0,
					"cornerText": "现金",
					"highLight": false,
					"award": "0.5",
					"awardType": 1,
					"awardUnit": "元"
				},
				{
					"day": 4,
					"coin": 0,
					"multiple": 0,
					"bottomText": "4天",
					"topText": "",
					"lastSignDay": false,
					"iconType": 8,
					"signed": false,
					"today": false,
					"supplySignMultiple": 0,
					"cornerText": "",
					"highLight": false,
					"award": "1000",
					"awardType": 2,
					"awardUnit": ""
				},
				{
					"day": 5,
					"coin": 0,
					"multiple": 0,
					"bottomText": "5天",
					"topText": "",
					"lastSignDay": false,
					"iconType": 8,
					"signed": false,
					"today": false,
					"supplySignMultiple": 0,
					"cornerText": "",
					"highLight": false,
					"award": "100",
					"awardType": 2,
					"awardUnit": ""
				},
				{
					"day": 6,
					"coin": 0,
					"multiple": 0,
					"bottomText": "6天",
					"topText": "",
					"lastSignDay": false,
					"iconType": 8,
					"signed": false,
					"today": false,
					"supplySignMultiple": 0,
					"cornerText": "",
					"highLight": false,
					"award": "1000",
					"awardType": 2,
					"awardUnit": ""
				},
				{
					"day": 7,
					"coin": 0,
					"multiple": 0,
					"bottomText": "7天",
					"topText": "",
					"lastSignDay": false,
					"iconType": 6,
					"signed": false,
					"today": false,
					"supplySignMultiple": 0,
					"cornerText": "现金",
					"highLight": false,
					"award": "0.3",
					"awardType": 1,
					"awardUnit": "元"
				},
				{
					"day": 9,
					"coin": 0,
					"multiple": 0,
					"bottomText": "9天",
					"topText": "",
					"lastSignDay": false,
					"iconType": 6,
					"signed": false,
					"today": false,
					"supplySignMultiple": 0,
					"cornerText": "现金",
					"highLight": false,
					"award": "0.3",
					"awardType": 1,
					"awardUnit": "元"
				},
				{
					"day": 11,
					"coin": 0,
					"multiple": 0,
					"bottomText": "11天",
					"topText": "",
					"lastSignDay": false,
					"iconType": 6,
					"signed": false,
					"today": false,
					"supplySignMultiple": 0,
					"cornerText": "现金",
					"highLight": false,
					"award": "0.5",
					"awardType": 1,
					"awardUnit": "元"
				},
				{
					"day": 14,
					"coin": 0,
					"multiple": 0,
					"bottomText": "14天",
					"topText": "",
					"lastSignDay": true,
					"iconType": 7,
					"signed": false,
					"today": false,
					"supplySignMultiple": 0,
					"cornerText": "现金",
					"highLight": false,
					"award": "2",
					"awardType": 1,
					"awardUnit": "元"
				}
			],
			"firstIndex": 1,
			"lastDays": 1,
			"todaySigned": false,
			"imageInfo": {
				"url": "https://ali.static.yximgs.com/udata/pkg/cloudcdn/nebula-img/nebula-signin-popup-bg-common.4847983a40d797e3.png",
				"type": 1,
				"className": "normal"
			},
			"buttonInfo": {
				"text": "立即签到",
				"type": 2,
				"jumpUrl": "",
				"cornerText": null,
				"showType": 0,
				"awardNum": 0,
				"styleType": 0,
				"jsBridgeParams": null
			},
			"bannerInfo": null,
			"bubbleText": "",
			"headText": "",
			"activity": false,
			"subButtonInfo": null,
			"nebulaSignCalendarEventView": {
				"eventSet": "",
				"closeAction": false,
				"limitCount": 3,
				"remindHasPaid": false,
				"calendarEventList": [
					{
						"title": "【快手极速版】签到啦～ 每天签到累积17888快乐豆",
						"note": "点击签到: https://n.ksurl.cn/btI6KoOZ\n关闭提醒: https://n.ksurl.cn/rXcMIg0W",
						"startDay": "1652401980000",
						"endDay": "1654907580000"
					},
					{
						"title": "【快手极速版】断签提醒，断签或损失6666快乐豆",
						"note": "点击签到: https://n.ksurl.cn/btI6KoOZ\n关闭提醒: https://n.ksurl.cn/bL2IlLkw",
						"startDay": "1652434380000",
						"endDay": "1654939980000"
					}
				],
				"todaySigned": false
			},
			"supplyTaskInfo": null,
			"oldAwardList": null,
			"playSupplyFinishAnimation": false,
			"supplyTaskFinish": false,
			"supplyFinishToast": null,
			"strategyOptimiAb": true,
			"signToGet": "4",
			"signPanelBtnAb": true,
			"encourageSignIn": true
		}
	},
	"host-name": "public-xm-kcs-node848.idczw.hb1.kwaidc.com"
}

