aa = {
	"result": 1,
	"trace_id": 652405125740977358,
	"host-name": "public-jswg-kcs-node562.idcyz.hb1.kwaidc.com",
	"data": {
		"totalCash": "7.2",
		"totalCoin": "3984",
		"allCash": "7.2",
		"showWithdrawButton": false,
		"coinExchangeTips": "",
		"banner": null,
		"toastInfo": null,
		"popup": null,
		"festivalPopup": null,
		"commonAwardPopup": null,
		"warningPopup": null,
		"noticePopup": null,
		"followAwardPopup": null,
		"assistancePopup": null,
		"fillPersonalDataAwardPopup": null,
		"mobileGameAwardPopup": null,
		"publishPhotoAwardPopup": null,
		"dailyTasks": null,
		"nebulaSignInPopup": null,
		"nebulaSupplySignInPopup": null,
		"coinExchangeGuidePopup": null,
		"withdrawChangePopup": null,
		"nebulaNewUserCashPopup": null,
		"treasureBoxPopup": null,
		"nebulaNoviceTask": null,
		"wechatShareResPopup": null,
		"regressCoinPopup": null,
		"bottomBanner": null,
		"shareConfig": null,
		"tokenShare": null,
		"weChatSharePop": null,
		"invitation": null,
		"autoSignIn": false,
		"helpSignPopup": null,
		"iosGreenInvitation": false,
		"clientIp": "112.232.43.162",
		"compensateAwardPopup": null,
		"cashCoinDataError": false,
		"xinHuiCashSignInPopup": null,
		"xinHuiCashOrCoinSignInPopup": null,
		"xinHuiGoldenAreaTaskType": null,
		"nebulaGoldenAreaTask": null,
		"inspireSinkPopup": null,
		"dailyCashPopup": null,
		"withDrawGuidePopup": null,
		"pushAwardGesture": null,
		"unLoginRegressCoinPopup": null,
		"monthlyCardPopup": null,
		"kwaiShopPopup": null,
		"userData": {
			"nickname": "正在缓冲99％",
			"avatar": "http://p5.a.yximgs.com/uhead/AB/2021/12/05/10/BMjAyMTEyMDUxMDA0MzNfMjY2OTAzMzc3M18yX2hkMjEyXzE1MA==_s.jpg",
			"posterDesc": null
		},
		"shareData": null,
		"theme": "",
		"iosReviewSwitch": false,
		"v2AbValue": 1,
		"unLoginWithdrawPageAbValue": 0,
		"moduleList": [
			[
				{
					"id": 1,
					"name": "banner",
					"desc": "顶部banner",
					"imgUrl": "",
					"linkUrl": "",
					"linkType": 0,
					"status": true,
					"bizId": 1,
					"extInfo": {}
				}
			],
			[
				{
					"id": 1,
					"name": "裂变",
					"desc": "裂变",
					"imgUrl": "https://ali.static.yximgs.com/udata/pkg/nebula/nebula-earning-card-invite-3.png",
					"linkUrl": "",
					"linkType": 0,
					"status": true,
					"bizId": 2,
					"extInfo": {}
				},
				{
					"id": 2,
					"name": "周周拉活",
					"desc": "周周拆红包",
					"imgUrl": "https://ali.static.yximgs.com/udata/pkg/nebula/earning-activity-card/daily-inivte-3.png",
					"linkUrl": "https://nebula.kuaishou.com/nebula/daily-invite?layoutType=4&source=EARNING_DIVERSION",
					"linkType": 2,
					"status": true,
					"bizId": 4,
					"extInfo": {}
				}
			]
		],
		"showGuide": false,
		"userGrade": 2,
		"newWithdrawType": 3,
		"sharePanelText": null,
		"sharePanelJumpEnum": null,
		"navBarNotificationResponse": null,
		"ftfExtraAward": null,
		"supplySignInAbTest": 0,
		"manualExchange": false,
		"exchangeCoinState": 0,
		"showFaq": true,
		"happyBeanPeriod": "",
		"happyBeanPopup": null,
		"moneyUnit": null,
		"dailyTaskText": null,
		"levelView": null,
		"inspirePopup": null,
		"skin": "",
		"v3AbValue": 2,
		"nebulaResourceActivityViewList": null,
		"unloginCoinAmount": 0,
		"unloginTaskCountDownTime": 0,
		"consumptionList": [
			{
				"id": 0,
				"icon": "https://static.yximgs.com/udata/pkg/NEBULA/chongzhizhongxin.png",
				"name": "话费充值",
				"linkUrl": "https://app.kwaixiaodian.com/merchant/shop/recharge/center?layoutType=4&showType=16",
				"linkType": 2,
				"bubble": {
					"startTime": 1653408000000,
					"endTime": 1654444799000,
					"text": "立减"
				}
			},
			{
				"id": 0,
				"icon": "https://static.yximgs.com/udata/pkg/NEBULA/choudajiang.png",
				"name": "抽大奖",
				"linkUrl": "https://nebula.kuaishou.com/activity/draw/main?layoutType=4&source=NEBULA_TASK",
				"linkType": 2,
				"bubble": null
			},
			{
				"id": 4,
				"icon": "https://static.yximgs.com/udata/pkg/NEBULA/jinbishangcheng.png",
				"name": "金币商城",
				"linkUrl": "https://encourage.kuaishou.com/activity/coin-mall/home?layoutType=4&source=ENTRY_ICON_BUTTON",
				"linkType": 2,
				"bubble": null
			}
		],
		"overSea": false,
		"limit": false,
		"isIosHidden": false
	}
}