a = {
  id: "43da6063-7700-46dd-976e-dc591ba89bdd",
  code: "200",
  message: "OK",
  result: [
    {
      id: 1,
      firstInfo: 0,
      firstInfoStatus: 1,
      firstInfoExp: 100,
      firstInfoIntegral: 50,
      inviteFriendsStatus: 0,
      inviteFriendsInfoStatus: 1,
      inviteFriendsExp: 10,
      inviteFriendsIntegral: 0,
      inviteFriendsAstrictStatus: 1,
      inviteFriendsAstrictCount: 5,
      firstReadStatus: 1,
      firstReadExp: 10,
      firstReadIntegral: 0,
      repetitionReadStatus: 0,
      repetitionReadExp: 10,
      repetitionReadIntegral: 0,
      readTimeStatus: 1,
      readTime: 20,
      yzOrderPoints: 1,
      companyId: 52,
      createTime: "2021-12-30 23:33:21",
      updateTime: "2022-01-20 22:50:51",
      overrun: false,
    },
  ],
  error: "",
};
